version: '3.9'
services: 
  db: 
    image: mcr.microsoft.com/mssql/server:2022-latest 
    container_name: mssql 
    hostname: mssql_host 
    restart: always 
    environment: 
      MSSQL_SA_PASSWORD: Hunter21! 
      ACCEPT_EULA: Y 
    ports: 
      - 1433:1433 
    networks: 
      - default 
      
networks: 
  default: 
    external: 
      name: local_network 
      
volumes: 
  mssql_data: